name: Practice Work

on:
      push:
            branches:
                  - main
      
      pull_request:
            branches:
                  - main


jobs:
      validate:

            runs-on: ubuntu-latest

            steps:
                  - name: Checkout Code
                    uses: actions/checkout@v4

                  - name: Show Files
                    uses: ls -la
                  
                  - name: Verify Required Files
                    run: |
                        test -f index.html